### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by miyemicodes**

### CODE REVIEW

**Comment by PrincessMaggy** [comment]
I can't merge this. Please fix the conflicts you have.

**Comment by miyemicodes** [comment]
corrected the issues i saw but its failing, i don't know why

**Comment by PrincessMaggy** [comment]
It's coming from your package,json file.

**Comment by miyemicodes** [comment]
fixed the conflicts i saw but it's still failing

**Comment by PrincessMaggy** [comment]
Please fix the conflicts you have in your app.js and referral.js. Do a pull from the base repo before doing that.

**Pull request closed without merging**
